FROM tethysplatform/tethys-core:dev-py3.12-dj3.2


ARG MAMBA_DOCKERFILE_ACTIVATE=1

#############
# ADD FILES #
#############

COPY apps ${TETHYS_HOME}/apps
COPY requirements/*.txt .

########################
# INSTALL APPLICATIONS #
########################
RUN pip install --no-cache-dir --quiet -r piprequirements.txt && \
    micromamba install --yes -c conda-forge --file requirements.txt && \
    micromamba clean --all --yes && \
    cd ${TETHYS_HOME}/apps/tethysapp-geoglows_dashboard && tethys install -w -N -q && \
    cd ${TETHYS_HOME}/apps/ggst && tethys install -w -N -q && \
    cd ${TETHYS_HOME}/apps/gwdm && tethys install -w -N -q

# Final Image Build
FROM tethysplatform/tethys-core:dev-py3.12-dj3.2 as build

COPY config/apps/post_setup_gwdm.py ${TETHYS_HOME}

COPY salt/ /srv/salt/

ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN rm -Rf ~/.cache/pip && \
    # micromamba install --yes -c conda-forge numpy==1.26.4 && \
    micromamba clean --all --yes

EXPOSE 80
CMD bash run.sh